# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-20 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_palestra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='palestra',
        ),
    ]
