# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-20 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('nome_palestrante', models.CharField(max_length=50)),
                ('descricao_palestra', models.TextField()),
                ('data_da_palestra', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_termino', models.TimeField()),
                ('link_apresentacao', models.URLField()),
            ],
        ),
    ]
